#!/usr/bin/env python3
"""
scaffold.py — 阶段 3：生成 Stata / R / Python 代码骨架

根据策略 + brief 自动生成 6 个标准 do-file（或 R 脚本），
覆盖：数据加载 → 描述统计 → 主回归 → 稳健性 → 异质性 → 表/图导出。

用法:
    python scripts/scaffold.py --strategy DiD --session my-paper --lang stata
    python scripts/scaffold.py --strategy RDD --session my-paper --lang r
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

# ============ 模板字典 ============

STATA_TEMPLATES = {
    'DiD': {
        '00_master.do': '''* ============================================================
* {session} - DiD analysis master file
* Generated by econ-paper-studio at {ts}
* ============================================================

clear all
set more off
cd "outputs/{session}/"

* 顺序执行所有子文件
do "do/01_clean.do"
do "do/02_descriptive.do"
do "do/03_main.do"
do "do/04_robustness.do"
do "do/05_heterogeneity.do"
do "do/99_export.do"

di "Done."
''',
        '01_clean.do': '''* ============================================================
* 01_clean.do — 数据加载与清洗
* ============================================================

* 读入原始数据
use "data/raw.dta", clear

* 关键变量必须有
keep if !missing(y, treat, post, id, year)

* 生成 DiD 交互项
gen did = treat * post
label var did "DiD interaction (treat × post)"

* 处理离群值（按需 winsorize）
* winsor2 y, replace cuts(1 99)

* 保存清洗后数据
save "data/clean.dta", replace
''',
        '02_descriptive.do': '''* ============================================================
* 02_descriptive.do — 描述统计 + 平衡性检验
* ============================================================
use "data/clean.dta", clear

* 全样本描述
sum y treat post controls*, detail

* 治疗组 vs 控制组（pre-period）平衡
preserve
keep if post == 0
table1_mc, by(treat) vars(y contn \\\\ controls* contn)
restore

* 输出表 1
estpost summarize y treat post controls*, detail
esttab using "tables/T1_descriptive.rtf", cells("mean(fmt(2)) sd(fmt(2)) min(fmt(2)) max(fmt(2))") replace
''',
        '03_main.do': '''* ============================================================
* 03_main.do — 主回归
* ============================================================
use "data/clean.dta", clear

* TWFE 基准（注意：错时治疗时有负权重问题，看 04_robustness 里的 CS-DiD）
reghdfe y did controls*, absorb(id year) cluster(id)
est store m1

* 加入治疗组×时间趋势
reghdfe y did controls* i.treat#c.year, absorb(id year) cluster(id)
est store m2

* 输出表 2
esttab m1 m2 using "tables/T2_main.rtf", ///
    star(* 0.10 ** 0.05 *** 0.01) ///
    se ar2 replace ///
    title("Main DiD Results") ///
    coeflabels(did "Treatment Effect")
''',
        '04_robustness.do': '''* ============================================================
* 04_robustness.do — 稳健性检验
* ============================================================
use "data/clean.dta", clear

* 1. 事件研究图（平行趋势检验）
gen event_time = year - first_treat_year if treat == 1
replace event_time = 0 if missing(event_time)
forvalues k = -5/5 {{
    gen lead_lag_`=`k'+5' = (event_time == `k') if treat == 1
}}
reghdfe y lead_lag_* controls*, absorb(id year) cluster(id)
coefplot, keep(lead_lag_*) vertical yline(0) ///
    title("Event Study") ///
    saving("figures/F1_event_study.gph", replace)

* 2. CS-DiD（错时治疗推荐，Callaway-Sant'Anna 2021）
* 需安装：ssc install csdid
* csdid y controls*, ivar(id) time(year) gvar(first_treat_year)
* csdid_estat group
* csdid_estat event

* 3. 安慰剂：虚假治疗时间（提前 3 年）
gen post_placebo = (year >= first_treat_year - 3)
gen did_placebo = treat * post_placebo
reghdfe y did_placebo controls*, absorb(id year) cluster(id)
est store mp1

* 4. 主样本删减后回归（剔除前 5%/后 5%）
* preserve
*   keep if y > pctile(y, 5) & y < pctile(y, 95)
*   reghdfe y did controls*, absorb(id year) cluster(id)
*   est store m_trim
* restore

* 5. 多重检验校正（多个 outcome / subgroup 时必做）
* 推荐优先报告 Holm 或 Romano-Wolf；简单场景至少报告 Bonferroni。
* 示例：
*   * ssc install rwolf
*   * rwolf y1 y2 y3, indepvar(did) controls(controls*) ///
*   *     absorb(id year) cluster(id) reps(999)
*   * Bonferroni adjusted alpha = 0.05 / number_of_outcomes

esttab mp1 using "tables/T3_robustness.rtf", se ar2 replace
''',
        '05_heterogeneity.do': '''* ============================================================
* 05_heterogeneity.do — 异质性效应
* ============================================================
use "data/clean.dta", clear

* 按所有制（国企 vs 民企）
reghdfe y c.did##i.soe controls*, absorb(id year) cluster(id)
est store h1

* 按规模（大企业 vs 小企业）
gen large = (size > pctile(size, 50))
reghdfe y c.did##i.large controls*, absorb(id year) cluster(id)
est store h2

esttab h1 h2 using "tables/T4_heterogeneity.rtf", se ar2 replace ///
    title("Heterogeneity")
''',
        '99_export.do': '''* ============================================================
* 99_export.do — 输出最终表 / 图
* ============================================================
* 已经在前面各 do-file 里输出，本文件用于一次性整合输出和清理临时文件
* 可选：把所有 *.rtf 拼接成 paper_tables.docx
'''
    },
    # 其他策略可以添加
    'RDD': {
        '00_master.do': '''* {session} - RDD master file ({ts})
clear all
do "do/01_clean.do"
do "do/02_descriptive.do"
do "do/03_main.do"
do "do/04_robustness.do"
''',
        '03_main.do': '''* RDD main regression
* 需要：ssc install rdrobust, rddensity
use "data/clean.dta", clear

* 主估计：CCT bandwidth + 局部线性
rdrobust y running_var, c(0) p(1) bwselect(mserd)
est store m_main

* RD plot
rdplot y running_var, c(0) graph_options(title("RD Plot") saving("figures/F1_rd.gph", replace))

esttab m_main using "tables/T1_main.rtf", se replace
''',
        '04_robustness.do': '''* RDD 稳健性
use "data/clean.dta", clear

* 1. McCrary 密度检验（防止操纵）
rddensity running_var, c(0)

* 2. 替代 bandwidth（CCT vs IK vs 自定义）
rdrobust y running_var, c(0) bwselect(mserd)
rdrobust y running_var, c(0) bwselect(certwo)
rdrobust y running_var, c(0) h(0.5)

* 3. Donut RD（剔除 cutoff 附近）
rdrobust y running_var if abs(running_var) > 0.05, c(0)

* 4. 安慰剂 cutoff
rdrobust y running_var, c(-0.2)
rdrobust y running_var, c(0.2)
'''
    },
}

R_TEMPLATES = {
    'DiD': {
        '00_main.R': '''# {session} - DiD analysis ({ts})
library(fixest)
library(did)        # Callaway-Sant'Anna
library(HonestDiD)  # Sensitivity

source("R/01_did_csa.R")
source("R/02_event_study.R")
source("R/03_honest_did.R")
source("R/99_plots.R")
''',
        '01_did_csa.R': '''# CS-DiD estimation (Callaway-Sant'Anna 2021)
df <- read.csv("data/clean.csv")

att_gt <- att_gt(yname = "y", tname = "year", idname = "id",
                 gname = "first_treat_year", data = df, control_group = "notyettreated")

agg_simple <- aggte(att_gt, type = "simple")
agg_dynamic <- aggte(att_gt, type = "dynamic")

print(summary(agg_simple))
print(summary(agg_dynamic))
ggdid(agg_dynamic) + ggsave("figures/F1_event_study.pdf", width = 8, height = 5)
''',
        '02_event_study.R': '''# Event study via fixest::feols
library(fixest)
df <- read.csv("data/clean.csv")
df$event_time <- df$year - df$first_treat_year

m <- feols(y ~ i(event_time, ref = -1) | id + year, df, cluster = ~id)
iplot(m, main = "Event Study", xlab = "Years from treatment")
''',
        '03_honest_did.R': '''# HonestDiD sensitivity
library(HonestDiD)
# (assume `att_gt` from 01_did_csa.R)
sens <- createSensitivityResults_relativeMagnitudes(
    att = att_gt, periodIdx = c(1, 2, 3), Mvec = seq(0, 2, by = 0.5))
print(sens)
'''
    }
}


def write_files(out_dir: Path, files: dict[str, str], session: str, ts: str) -> list[Path]:
    written: list[Path] = []
    for name, content in files.items():
        p = out_dir / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content.format(session=session, ts=ts), encoding='utf-8')
        written.append(p)
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description='Generate code scaffold for empirical analysis.')
    parser.add_argument('--strategy', required=True,
                        choices=['DiD', 'RDD', 'IV', 'SCM', 'PSM', 'DML'])
    parser.add_argument('--session', required=True)
    parser.add_argument('--lang', default='stata', choices=['stata', 'r', 'python'])
    parser.add_argument('--output-dir', default='outputs')
    args = parser.parse_args()

    base = Path(args.output_dir) / args.session
    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    if args.lang == 'stata':
        templates = STATA_TEMPLATES.get(args.strategy)
        out = base / 'do'
    elif args.lang == 'r':
        templates = R_TEMPLATES.get(args.strategy)
        out = base / 'R'
    else:
        print(f'[error] Python templates for {args.strategy} not yet implemented. Use --lang stata or --lang r.',
              file=sys.stderr)
        return 1

    if not templates:
        print(f'[error] No template for strategy {args.strategy} in lang {args.lang}', file=sys.stderr)
        return 1

    # 创建 session 目录结构
    for sub in ('data', 'tables', 'figures', 'robustness'):
        (base / sub).mkdir(parents=True, exist_ok=True)

    written = write_files(out, templates, args.session, ts)

    print('=' * 70)
    print(f'Generated {len(written)} files for {args.strategy} ({args.lang}) in {base}/')
    print('=' * 70)
    for p in written:
        print(f'  {p}')
    print()
    print('Next:')
    print(f'  1. cd {base}')
    print(f'  2. Put your raw data in data/raw.{"dta" if args.lang == "stata" else "csv"}')
    print(f'  3. Edit {written[0].name} to set the right variable names')
    print(f'  4. Run from {args.lang}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
